version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
#  nodejs:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: nodejs
#    container_name: nodejs
#    restart: unless-stopped
#    env_file: .env
#    environment:
#      - MONGO_USERNAME=root
#      - MONGO_PASSWORD=example
#      - MONGO_HOSTNAME=localhost
#      - MONGO_PORT=27017
#      - MONGO_DB=MyPackageDev
#    ports:
#      - '80:8080'
#    volumes:
#      - '.:/home/node/app'
#      - './node_modules:/home/node/app/node_modules'
#    command: './home/node/app/node_modules/nodemon/bin/nodemon.js src/main.js'
